### ISSUE TITLE
Still maintained ?

### ISSUE THREAD

**Issue by gedw99** [yomorun/presencejs#10]
I saw in the read e about the new repo.

Is this repo not worth basing off anymore.

I wam using the  presence golang code , so I will fork or maybe port over to a different presence system.

**Comment by fanweixiao** [comment]
Hi @gedw99 ,the golang code will always work. the new repo is still in experience stage, trying to work on webtransport directly.

**Comment by gedw99** [comment]
Thanks @fanweixiao 

Ok I will stick with this golang repo then .
